<a href="https://colab.research.google.com/github/Lauralug0/Facebook/blob/main/Lab_Exercise_3_by_Laura_Lugo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [25]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

a = np.array([[5, 2, 3], [6, 1, 3],[2, 4, 1]])
b = np.array([[5, 2, 3], [6, 1, 3], [2, 4, 1]])
c = np.array([[5, 2, 3], [6, 1, 3],[2, 4, 1]])


print("Array A:\n", a)
print("Array B:\n", b)
print("Array C:\n", b)

d = np.array([[4, -7, 4],[5, 6, -1],[-4, 2, 5]])

print("Array D:\n", d)

ad = np.matmul(a, d)
da = np.matmul(d, a)

print("Matrix A:\n", a)
print("Matrix D:\n", d)
print("Matrix AD:\n", ad)
print("Matrix DA:\n", da)

print("Are AD and DA equal?", np.array_equal(ad, da))


det_B = np.linalg.det(b)
print("\n Determinant of B:", round(det_B))


B_inv = np.linalg.inv(b)
print("Inverse of B:\n", B_inv)


D_inv = np.linalg.inv(d)
print("Inverse of D:\n", D_inv)

Inv1 = np.matmul(d, D_inv)
Inv2 = np.matmul(D_inv, d)



print("D * D⁻¹:\n", np.round(Inv1, decimals=5))
print("D⁻¹ * D:\n", np.round(Inv2, decimals=5))
print("Both matrices are identical")

Array A:
 [[5 2 3]
 [6 1 3]
 [2 4 1]]
Array B:
 [[5 2 3]
 [6 1 3]
 [2 4 1]]
Array C:
 [[5 2 3]
 [6 1 3]
 [2 4 1]]
Array D:
 [[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]
Matrix A:
 [[5 2 3]
 [6 1 3]
 [2 4 1]]
Matrix D:
 [[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]
Matrix AD:
 [[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
Matrix DA:
 [[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]
Are AD and DA equal? False

 Determinant of B: 11
Inverse of B:
 [[-1.          0.90909091  0.27272727]
 [ 0.         -0.09090909  0.27272727]
 [ 2.         -1.45454545 -0.63636364]]
Inverse of D:
 [[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]]
D * D⁻¹:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]
D⁻¹ * D:
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
Both matrices are identical
